version: "3.8"

services:
    localstack:
      container_name: localstack-container
      image: localstack/localstack
      ports:
        - "443:443"
        - "4566:4566"
        - "4571:4571"
        - "8080:8080"
      environment:
        - DEBUG=1
        - DATA_DIR=/tmp/localstack/data # Local directory for saving persistent data
        - DEFAULT_REGION=us-east-1
        - LAMBDA_EXECUTOR=local #running lambda from local dir
        - LAMBDA_REMOTE_DOCKER=0
        - PORT_WEB_UI=8080
        - DOCKER_HOST=unix:///var/run/docker.sock
        - HOST_TMP_FOLDER=/tmp/localstack
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"